# copied from https://gist.github.com/orcema/c282c72ddc549060fb10999dbe774526
blueprint:
  name: ZHA - IKEA STYRBAR/TRADFRI - Color Lights
  description:
    This automation simulates the use of the IKEA TRADFRI remote control
    connected through ZHA.
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote control 4 buttons
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain: light
    speed:
      name: Speed
      description: The speed in which to update the light when the button is held.
      selector:
        number:
          min: 100.0
          max: 1000.0
          step: 100.0
          unit_of_measurement: milliseconds
          mode: slider
      default: 500
mode: restart
max_exceeded: silent
variables:
  var_light: !input "light"
  var_speed: !input "speed"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness: 255
              rgb_color: [255, 170, 94]
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input "light"
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness_step_pct: 20
              transition: "{{ (var_speed / 1000)|float }}"
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness_step_pct: -20
              transition: "{{ (var_speed / 1000)|float }}"
      - conditions: # press right or left arrow button
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              rgb_color:
                - >
                  {% if state_attr(var_light, "rgb_color")[0] == 255 and state_attr(var_light, "rgb_color")[1] == 170 and state_attr(var_light, "rgb_color")[2] // 10 == 9 %}
                    {% set high = 0 %}
                    {% set middle = 0 %}
                    {% set low = 0 %}
                  {% else %}
                    {% set high = (state_attr(var_light, "rgb_color")[0] // 250) %}
                    {% set middle = (state_attr(var_light, "rgb_color")[1] // 250) %}
                    {% set low = (state_attr(var_light, "rgb_color")[2] // 250) %}
                  {% endif %}
                  {% set current = high * 4 + middle * 2 + low %}
                  {% set next = (current + (1 - (2 * (257 - trigger.event.data.params.param1)))) % 8 %}
                  {% if next == 0 %}
                    255
                  {% else %}
                    {{((next // 4) % 2) * 255}}
                  {% endif %}
                - >
                  {% if state_attr(var_light, "rgb_color")[0] == 255 and state_attr(var_light, "rgb_color")[1] == 170 and state_attr(var_light, "rgb_color")[2] // 10 == 9 %}
                    {% set high = 0 %}
                    {% set middle = 0 %}
                    {% set low = 0 %}
                  {% else %}
                    {% set high = (state_attr(var_light, "rgb_color")[0] // 250) %}
                    {% set middle = (state_attr(var_light, "rgb_color")[1] // 250) %}
                    {% set low = (state_attr(var_light, "rgb_color")[2] // 250) %}
                  {% endif %}
                  {% set current = high * 4 + middle * 2 + low %}
                  {% set next = (current + (1 - (2 * (257 - trigger.event.data.params.param1)))) % 8 %}
                  {% if next == 0 %}
                    170
                  {% else %}
                    {{((next // 2) % 2) * 255}}
                  {% endif %}
                - >
                  {% if state_attr(var_light, "rgb_color")[0] == 255 and state_attr(var_light, "rgb_color")[1] == 170 and state_attr(var_light, "rgb_color")[2] // 10 == 9 %}
                    {% set high = 0 %}
                    {% set middle = 0 %}
                    {% set low = 0 %}
                  {% else %}
                    {% set high = (state_attr(var_light, "rgb_color")[0] // 250) %}
                    {% set middle = (state_attr(var_light, "rgb_color")[1] // 250) %}
                    {% set low = (state_attr(var_light, "rgb_color")[2] // 250) %}
                  {% endif %}
                  {% set current = high * 4 + middle * 2 + low %}
                  {% set next = (current + (1 - (2 * (257 - trigger.event.data.params.param1)))) % 8 %}
                  {% if next == 0 %}
                    94
                  {% else %}
                    {{((next // 1) % 2) * 255}}
                  {% endif %}
              transition: "{{ (var_speed / 1000)|float }}"
    default: []