

# copied from https://gist.github.com/orcema/c282c72ddc549060fb10999dbe774526
blueprint:
  name: ZHA - IKEA STYRBAR/TRADFRI - Color Lights
  description:
    This automation simulates the use of the IKEA TRADFRI remote control
    connected through ZHA.
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote control 4 buttons
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain: light
    speed:
      name: Speed
      description: The speed in which to update the light when the button is held.
      selector:
        number:
          min: 100.0
          max: 1000.0
          step: 100.0
          unit_of_measurement: milliseconds
          mode: slider
      default: 500
    default_color:
      name: Default Color
      description: The color of the light when turned on
      selector:
        color_temp:
          unit: mired
          min: 250
          max: 454
      default: 357
    default_brightness:
      name: Default brightness
      description: The brightness of the light when turned on.
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: slider
      default: 255
    steps:
      name: color steps
      description: The steps to change the color in the xy color model. Tipping the "left" or "right" button will change the color of the light by this amount.
      selector:
        number:
          min: 0.1
          max: 0.5
          step: 0.001
          mode: slider
      default: 0.2
mode: restart
max_exceeded: silent
variables:
  var_light: !input "light"
  var_speed: !input "speed"
  var_default_color: !input "default_color"
  var_default_brightness: !input "default_brightness"
  var_steps: !input "steps"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness: "{{ var_default_brightness }}"
              color_temp: "{{ var_default_color }}"
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input "light"
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness_step_pct: 20
              transition: "{{ (var_speed / 1000)|float }}"
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              brightness_step_pct: -20
              transition: "{{ (var_speed / 1000)|float }}"
      - conditions: # press right or left arrow button
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light"
            data:
              xy_color:
                - >-
                  {% set x = state_attr(var_light, "xy_color")[0] %}
                  {% set y = state_attr(var_light, "xy_color")[1] %}
                  {% set step = (1 - (2 * (257 - trigger.event.data.params.param1))) * var_steps %}
                  {% set nextY = y + step %}
                  {% if nextY > 1 %}
                    {% set nextX = x + step %}
                    {% if nextX > 1 %}
                      {% set nextXVal = 0.0 %}
                    {% else %}
                      {% set nextXVal = nextX %}
                    {% endif %}
                  {% else %}
                    {% if nextY < 0 %}
                      {% set nextX = x + step %}
                      {% if nextX < 0 %}
                        {% set nextXVal = 1.0 %}
                      {% else %}
                        {% set nextXVal = nextX %}
                      {% endif %}
                    {% else %}
                      {% set nextXVal = x %}
                    {% endif %}
                  {% endif %}
                  {{nextXVal}}
                - >-
                  {% set x = state_attr(var_light, "xy_color")[0] %}
                  {% set y = state_attr(var_light, "xy_color")[1] %}
                  {% set step = (1 - (2 * (257 - trigger.event.data.params.param1))) * var_steps %}
                  {% set nextY = y + step %}
                  {% if nextY > 1 %}
                    {% set nextYVal = 0.0 %}
                  {% else %}
                    {% if nextY < 0 %}
                      {% set nextYVal = 1.0 %}
                    {% else %}
                      {% set nextYVal = nextY %}
                    {% endif %}
                  {% endif %}
                  {{nextYVal}}
              transition: "{{ (var_speed / 1000)|float }}"
    default: []